const vehiclesActionTypes = {
  FETCH_VEHICLES_START: 'FETCH_VEHICLES_START',
  FETCH_VEHICLES_SUCCESS: 'FETCH_VEHICLES_SUCCESS',
  FETCH_VEHICLES_FAILURE: 'FETCH_VEHICLES_FAILURE',
  TOGGLE_VEHICLES_HIDDEN: 'TOGGLE_VEHICLES_HIDDEN',
  ADD_VEHICLE: 'ADD_VEHICLE',
  REMOVE_VEHICLE: 'REMOVE_VEHICLE',
  UPDATE_STOCK: 'UPDATE_STOCK'
};

export default vehiclesActionTypes;
