const planetsActionTypes = {
  FETCH_PLANETS_START: 'FETCH_PLANETS_START',
  FETCH_PLANETS_SUCCESS: 'FETCH_PLANETS_SUCCESS',
  FETCH_PLANETS_FAILURE: 'FETCH_PLANETS_FAILURE',
  SET_PLANET_ACTIVE: 'SET_PLANET_ACTIVE',
  ADD_PLANET: 'ADD_PLANET',
  REMOVE_PLANET: 'REMOVE_PLANET'
};

export default planetsActionTypes;
